name: CI
on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm i -g ajv-cli

      - name: Validate manifests against schemas
        run: |
          ajv validate -s schemas/apifee.schema.json -d "apifee.json" || true
          ajv validate -s schemas/usage-receipt.schema.json -d "examples/**/*.receipt.json" || true

      - name: Run CLI self-checks (if you have them)
        run: |
          if command -v agentapi >/dev/null 2>&1; then agentapi --help; fi
