name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Include .well-known + add .nojekyll
        run: |
          mkdir -p _site/.well-known
          # Copy from root .well-known if present
          if [ -d ".well-known" ]; then
            cp -R .well-known/* _site/.well-known/
          fi
          # Copy from docs/.well-known if you move it there in future
          if [ -d "docs/.well-known" ]; then
            mkdir -p _site/.well-known
            cp -R docs/.well-known/* _site/.well-known/
          fi
          # Ensure GitHub Pages serves raw files (no Jekyll on the artifact)
          touch _site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
